name: dagger_hackathon

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [dagger-hackathon-feat]

jobs:
  dagger-run-unit-tests:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.DAGGER_HACKATHON_GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CURRENT_BRANCH: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dagger CLI
        run: |
          curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create .env file
        working-directory: docs/dagger/dagger-hackathon/
        run: |
          cat <<EOF > .env
          OPENAI_BASE_URL=https://vdfvdf.openai.azure.com/
          OPENAI_MODEL=gpt-4o
          # OPENAI_API_KEY=${OPENAI_API_KEY}
          OPENAI_API_KEY=test_key
          OPENAI_AZURE_VERSION=2024-12-01-preview
          GITHUB_TOKEN=${GITHUB_TOKEN}
          GITHUB_TOKEN=test_token
          EOF

      - name: Dagger Run Unit Tests
        working-directory: docs/dagger/dagger-hackathon/
        # env:
        #   DAGGER_SECRET_GITHUB_TOKEN: ${{ secrets.DAGGER_HACKATHON_GITHUB_TOKEN }}
        run: printenv
